### ISSUE TITLE
Angular demo is not working

### ISSUE THREAD

**Issue by harishanandan** [g1eb/angular2-calendar-heatmap#12]
The demo link is not working please check it thanks apart from that nice job...

**Comment by g1eb** [comment]
Oh oh, looks like some of the resources are not loading properly.

Thanks for letting me know, I'll take a look.

**Comment by harishanandan** [comment]
Hi
Pls share if you have a demo project

**Comment by g1eb** [comment]
Hi, I've updated the core-js version that was missing a shim file, demo is back online at:
[https://rawgit.com/g1eb/angular2-calendar-heatmap/master/](https://rawgit.com/g1eb/angular2-calendar-heatmap/master/)

v0.1.9
