### ISSUE TITLE
Error in angular 8 Apllication

### ISSUE THREAD

**Issue by sunith-kumar** [g1eb/angular2-calendar-heatmap#13]
ERROR in ./node_modules/angular2-calendar-heatmap/dist/calendar-heatmap.js
Module not found: Error: Can't resolve 'd3/index' in 'D:\projects\Angular 8\machstatz\node_modules\angular2-calendar-heatmap\dist

**Comment by g1eb** [comment]
Hi! I've updated project dependencies, could you try again with the latest version?
Let me know if that works for you :)

v0.1.10

**Comment by sunith-kumar** [comment]
Hi @g1eb Thank you for updating project, Now working with angular 8

**Comment by g1eb** [comment]
Awesome, closing the issue then:)

**Comment by gabri3l0** [comment]
> Hi @g1eb Thank you for updating project, Now working with angular 8

How i can clone this project and run it, I installed cli and npm install and shows me "_The serve command requires to be run in an Angular project, but a project definition could not be found._"

**Comment by g1eb** [comment]
Ohh are you trying to run it for development purposes? Or as part of another project?
