### ISSUE TITLE
Support for label override

### ISSUE THREAD

**Issue by amoscatelli** [g1eb/angular2-calendar-heatmap#14]
Labels should be requested at runtime, to take account of the locale.

For example if you need the label for 'Week' you should call a function returning the label if such function is specified, or use the current behaviour.

I can contribute to the project myself, but I failed to build the project and produce a valid npm module.

Can you guide me a little ?

**Comment by g1eb** [comment]
Hi there! Thanks for the suggestion, sounds like a good idea to add this.

If you'd like to contribute, simply fork the repo, test your changes and submit a PR.

You don't have to build the project or generate the npm module.
Were you able to run the project in development?

**Comment by amoscatelli** [comment]
Ahh you mean I could test using the test app/module inside the app folder ?
What I wanted to do is to build the project and 'npm link' it in my real project.

**Comment by g1eb** [comment]
Oh I see, to build you can run `npm run build` - this should regenerate built files inside the dist folder. Using npm link creates a symlink and you can import the module in your project for testing.

Alternatively, you could use the demo included in the `app` folder.

Let me know if you run into anything, I can help with debugging.

**Comment by amoscatelli** [comment]
If I try to link the project in my project library it doesn't work :

ERROR: @angular/core/core.ts(756,18): Error during template compile of 'Component'
  Function calls are not supported in decorators.
Unexpected value 'CalendarHeatmap in C:/Users/amoscatelli/Documents/Visual Studio Code/angular2-calendar-heatmap/dist/calendar-heatmap.d.ts' declared by the module 'NgxVisiontechMaterialModule in C:/Users/amoscatelli/Documents/Visual Studio Code/ngx-visiontech/projects/ngx-visiontech-material/src/lib/ngx-visiontech-material.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

How can I use the demo in the app folter ? That is not an angular project ...

**Comment by amoscatelli** [comment]
#15

**Comment by amoscatelli** [comment]
Please help me testing.
I am confident it made only safe changes but please help since I couln't test it. (Read previous comment).

**Comment by g1eb** [comment]
Hi! Thanks for submitting the PR, I had a quick look, couple of things:

1. to test the changes you can use the app that comes with the lib (in the app folder)

You can use something like https://www.npmjs.com/package/serve to serve the files from the root folder, it should automatically pick up the changes you've made in the `src/calendar-heatmap.component.ts` (your browser might cache the source files, make sure you use hard-refresh to see the changes)

2. The error I get right out of the gate is the missing dependency on line 2: `import { UnaryFunction } from 'rxjs/interfaces';`

To fix this you'd have to update `rxjs` requirement to use a newer version, and perhaps even include the `rxjs-compat` package. We'd have to see what else this would break then. Is there any other way to work around this dependency requirement?

3. This is a minor detail but did you commit everything at the same time? Hard to tell what the progression is of the changes without specific commits.

Could you see if you can test this on your machine using the method described above? Thanks!

**Comment by amoscatelli** [comment]
1) Ok I'll try thank you
2) That's really strange, I did NOT change the package.json so I should be using the same rxjs version you are using, that is :

  "dependencies": {
    "d3": "^4.13.0",
    "lodash": "^4.17.14",
    "moment": "^2.24.0",
    "rxjs": "^5.5.12",
    "rxjs-compat": "^6.5.2"
  }

3) Yea sorry, maybe different commit would have been a better choice.

I'll test and let you know

**Comment by amoscatelli** [comment]
I am getting your error but I don't understand:

Error loading https://unpkg.com/rxjs@5.0.1/interfaces.js as "rxjs/interfaces" from http://localhost:5000/src/calendar-heatmap.component.ts

Why is it using a different version of rxjs when serving ?
I'll look into this ...

**Comment by amoscatelli** [comment]
Ok now everything should work.
I tested everything (every input function I created) and it's good for me.
Let me know.

**Comment by g1eb** [comment]
Thanks again for the update! Looks like it's working on my end too, good stuff.

Could you provide an example of how you would use your changes to override the labels?
I'm curious to see this addition work the way you intended it/ need for your project :)

Also why did you remove the `/dist` folder from the repo? AFAIK it did have a purpose. I think it was that we were using dist files hosted on raw github for some demos before (such as jsfiddle)

**Comment by amoscatelli** [comment]
I will send you the complete example after the pull is accepted as I need the new package (I didn't manage to make it work with npm link).

I removed /dist folder because AFAIK it's not a best practice to push compiled code, but if you want I can put it back.

**Comment by amoscatelli** [comment]
I pushed back the content of dist folder.

Is this ok now ?

**Comment by amoscatelli** [comment]
I am going to use ngx-translate and angular local support to have localized translation at runtime.
I will provide a snipshot of my code but I need the new library version as I 'npm link' didn't work for me and I can't test or integrate the new functionalities in my project.

If you want something simpler now, I tested the new functionalities by simply create a test method (inside your app.component.ts):

public test = value => 'HI THERE!' + value;

and then:

    <calendar-heatmap
      [data]="data"
      [color]="color"
      [overview]="overview"
      [formatTime]="test"
      [yearLabel]="test"
      [monthLabel]="test"
      [weekLabel]="test"
      [dayOfWeekLabel]="test"
      [timeLabel]="test"
      [buildGlobalTooltip]="test"
      [buildYearTooltip]="test"
      [buildMonthTooltip]="test"
      [buildWeekTooltip]="test"
      [buildDayTooltip]="test"
      (handler)="print($event)"
      (onChange)="handleOnChange($event)">
    </calendar-heatmap>

You will see all of your labels will be overridden.

**Comment by g1eb** [comment]
Thanks! I've published the update under v0.2.0, please let me know if that works for you.

**Comment by amoscatelli** [comment]
#16

**Comment by amoscatelli** [comment]
Yea it works. I just pushed a minor fix to handle empty array of data.

The workaround till the pull request is accepted is :

    this.calendar.data =
      this.calendar.data && this.calendar.data.length > 0 ?
        this.calendar.data :
        [
          <CalendarHeatmapData>{
            'details': []
          }
        ];

**Comment by g1eb** [comment]
Merged and published on npm.

v0.2.2
