### ISSUE TITLE
Not working with d3 version 4.7.4

### ISSUE THREAD

**Issue by kirtiesl** [g1eb/angular2-calendar-heatmap#4]
Hello,
Is this version compatible with angular 4 and latest version of d3 js?

**Comment by g1eb** [comment]
Hi Kirtiesl! Thanks for getting in touch again, I am still waiting for a reply in [your previous thread](https://github.com/g1eb/angular2-calendar-heatmap/issues/2). Were you able to resolve the issues there given the instructions and if so, can we close that thread now? :)

This library is compatible with @angular/core version 4.0.0 and d3 version 3.5.16
There is a [vanilla js version of this library](https://github.com/g1eb/calendar-heatmap) that is compatible with d3 version 4.10.2

Are you experiencing a specific issue when trying to run this project?

**Comment by g1eb** [comment]
Hm, does the heatmap work in your project if d3 version is switched back to 3.5.6? In other words, is d3 version the only problem to get the calendar heatmap working? 

I know that the vanilla js version works with d3 4.10.2 (as mentioned above) and we could look into updating this library in the same way to support latest version of d3 :)

**Comment by kirtiesl** [comment]
Yes, if I degrade my d3 version to 3.5.6 the library works perfect.

**Comment by kirtiesl** [comment]
Please let us know when will can this be upgraded to latest version of d3 ?

**Comment by g1eb** [comment]
I'll try to take a look somewhere this week. I'll let you know :)

**Comment by kirtiesl** [comment]
Thanks :) 
Hope the updated version will release soon!! Its really urgent

**Comment by g1eb** [comment]
Hi, I've added support for d3 version 4, let me know if that works for you :)

v0.1.1

**Comment by kirtiesl** [comment]
Still not working. 
I get this error ERROR Error: Uncaught (in promise): ReferenceError: d3 is not defined
ReferenceError: d3 is not defined
    at CalendarHeatmap.webpackJsonp.1937.CalendarHeatmap.ngAfterViewInit (calendar-heatmap.js:43)

**Comment by g1eb** [comment]
Hi kirtiesl, could you try again please? I've updated the way dependencies are imported.

v0.1.2

**Comment by g1eb** [comment]
Heya, did it work for you with the recent update? :)
I've also updated the demo to work with new imports and system js.

Let me know if you run into any problems.


v0.1.3

**Comment by g1eb** [comment]
Hi Kirtiesl, checking in to see if the import issue was resolved with the last update.

**Comment by kirtiesl** [comment]
Yes :) Thanks for the update.

**Comment by g1eb** [comment]
Terrific, closing this issue :)
