### ISSUE TITLE
Cannot find module 'calendar-heatmap'

### ISSUE THREAD

**Issue by dzero1** [g1eb/angular2-calendar-heatmap#5]
I got an error when I try to build a production build.

..../src/$$_gendir/node_modules/angular2-calendar-heatmap/dist/calendar-heatmap.ngfactory.ts (10,21): Cannot find module 'calendar-heatmap'.

So I made a fresh ng environment and try it again. But still same issue.

**Comment by g1eb** [comment]
Hi, can you provide an example of your setup? I just did a clean install with angular-cli to get a new project and it would build without any issues.

Also, make sure you import the heatmap from `angular2-calendar-heatmap`, like so:
```
import { CalendarHeatmap } from 'angular2-calendar-heatmap';
```

And include it in your NgModule declarations:
```
@NgModule({
  declarations: [
    CalendarHeatmap,
    ...
  ],
...
})
```

**Comment by dzero1** [comment]
here I attach a test that I done
https://drive.google.com/open?id=0Bx7NyKVVCxWrTUFMQnFsU2NUYmc

and im doing production build
`ng build --target=production --environment=prod`

**Comment by g1eb** [comment]
Hello again, I was able to reproduce this error (after adding a missing `.angular-cli.json` file and installing the main dependencies (d3, moment and angular2-calendar-heatmap).

I found some related issues on github and I'm looking into what exactly causes this error.

As a workaround for now you can try to build without aot:
`ng build --target=production --environment=prod --aot=false`

**Comment by dzero1** [comment]
Ok good. Thanks, But I want to build my ap with AoT. 
Waiting for the fix. (Y)

**Comment by g1eb** [comment]
I'm still looking into this one, I'll let you know as soon as it's fixed :)

**Comment by g1eb** [comment]
Hi again, sorry for the late reply, I've double checked and found that `moduleId` declared inside `tsconfig.json` was inappropriately set. I hope that fix takes care of your issue, please let me know if you run into anything else! :)

v0.1.4

**Comment by g1eb** [comment]
Hi, checking in to see if this was fixed already :)
Let me know if you run into more issues!

**Comment by g1eb** [comment]
Closing this for now, please reopen if this is still an issue ^
