### ISSUE TITLE
How to use calendar-heatmap component with other kinds of data

### ISSUE THREAD

**Issue by nfrik** [g1eb/angular2-calendar-heatmap#6]
Thank you for this great widget. I was wondering how one could use this heatmap with other kinds of data. For example I would like to use it display unemployment chronology similarly to bokeh plot here: https://bokeh.pydata.org/en/latest/docs/gallery/unemployment.html

**Comment by g1eb** [comment]
Hi, glad you like it :) Nice example too, similar use case!

The heatmap can be used if the unemployment data has timestamps with values (e.g. date in iso and value representing unemployment rate on that date). This would lead to the default calendar heatmap as you can see in the demo.

The 'name' parameter can be used to show different unemployment rates based on country, or market sector, or anything else. 

This calendar-heatmap was originally used in a project where data values are presented in hours/minutes/seconds - but that is just the presentation of it. If you need to present unemployment data in other units, feel free to fork and adjust as necessary.

**Comment by nfrik** [comment]
Thank you for your ideas!

**Comment by g1eb** [comment]
No problem at all :) If you end up tinkering with it and need any help let me know
