### ISSUE TITLE
Want to fetch the time period selected in the heatmap.

### ISSUE THREAD

**Issue by sandymantri** [g1eb/angular2-calendar-heatmap#8]
Hi, I wonder if its possible to fetch the time period(in terms of timestamp range or start date/end date), from the heatmap. 
I want to display some more data below the heatmap based on the time period.
Thank you in advance.

**Comment by g1eb** [comment]
Hi there! :) Interesting request, what view are we talking about here? Is it the daily overview or the year overview in the calendar? Also what is your preferred method of selecting a time period?

It's not in the library yet but could be a good feature if you would like it :)

**Comment by sandymantri** [comment]
So, in my case I am using library from Year till day view. My requirement is, when I am on year view(where i see all 12months) lets say for 2017, then other component below heat map should show data for whole year. Now, If i select one of the month, lets say Nov-2017 from the heat map, i should show only data for Nov-2017 in the other component.

So Ideally, there should be two veriables startDateTime and endDateTime based on the current view exported from library so that it will take care of all the cases.

I am glad that you are considering this feature for library. But for now is there any workaround using which i can make this work. Let me know. Thanks.

**Comment by g1eb** [comment]
Ahh, i see what you mean, should not be too hard to add the range feature :)

Basically what you need is an `onChange` event for when the users changes the overview, right? Maybe with some parameters like the selected overview type, start datetime object (moment) and end datetime object (moment). Would that be good enough?

**Comment by sandymantri** [comment]
Yes, That should be sufficient. This exactly what i want.

**Comment by g1eb** [comment]
Yeah, let me see if I can add that to the lib real quick, I'll get back to you when it's done

**Comment by sandymantri** [comment]
Okay.. Great! Please let me know. Thanks!

**Comment by g1eb** [comment]
Added a simple onChange handler that you can bind to, see [example](https://rawgit.com/g1eb/angular2-calendar-heatmap/master/)

Let me know if this works for you :)

v0.1.6

**Comment by sandymantri** [comment]
Hi.. Thanks for the update and its working like a charm for me when i am on month, week or a day view.. I think you have not emmited it for global view because there was no standard StartDate or EndDate for it. 
I was needing that too.. in my case when we are at global view we should not consider dates and show all available data.

**Comment by g1eb** [comment]
Ah, I see. In that case I'll add `onChange` event to the global overview with first date as the 'start' and last date as the 'end' - to be consistent with other views. If you don't actually need the start and end dates in global overview you can show all the data, is that okay? :)

v0.1.7

**Comment by sandymantri** [comment]
Hi... This worked. Thanks. There is one more issue with the library. Its with tooltip positioning. Its not considering relative position of the element within which heatmap is rendered. It y position is computed on the basis of week-day and x position is computed based on the week number. But no consideration is made about the parent element position within which heat map is rendered. This causing me issues while rendering the tooltip.

Also, tooltip content is very tightly coupled. Is there a way we can customise tooltip. May be you can provide one more handler and we can handle on our own what to display in tooltip box when we hover on element. I hope I am not asking for too much.

**Comment by g1eb** [comment]
Glad to hear it all worked out :)

With respect to the tooltip, it sounds like a different issue from the `onChange` event handler and i would like to ask you to open a separate issue for it, please. I would have to think of a good way to generalize the tooltip content and we can discuss it there :)

**Comment by sandymantri** [comment]
Okay. Will do.
Closing this issue.
